/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package kotlin_playground

import kotlin_playground.data.ObjectWithValidity
import java.time.Instant
import java.time.LocalDateTime
import java.util.*

class App {
  val greeting: String
    get() {
      return "Hello World!"
    }
}

fun main() {
  println(App().greeting)
  val data = ObjectWithValidity(validFrom = null, validTo = LocalDateTime.now())
  println(data.validTo)
  val values = listOf(1, 2, 3, 4, 5, 6, 7, 8, 9)
  val index = values.indexOf(5)
  println("Split at index $index ")
  //values.groupBy { it > 5 }.forEach { b, ints -> println("Sublist exists $b with $ints") }
  val grouped = values.groupBy { it > 5 }
  println("group true: ${grouped[true]}")
  println("group false: ${grouped[false]?.reversed() }")
  println("without 5: ${values.groupBy { it < 5 }[true]?.reversed() }")

}
