/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package kotlin_playground

import kotlin_playground.data.ObjectWithValidity
import java.time.Instant
import java.time.LocalDateTime
import java.util.*

class App {
  val greeting: String
    get() {
      return "Hello World!"
    }
}

fun main() {
  println(App().greeting)
  val data = ObjectWithValidity(validFrom = null, validTo = LocalDateTime.now())
  println(data.validTo)
  val index = 5
  val values: List<Int> = mutableListOf(1, 2, 3, 4, 5, 6, 7, 8, 9).also{ it.removeAt(it.indexOf(index)) }
  println("Split at index $index ")
  val grouped = values.groupBy { it > 5 }
  println("group true: ${grouped[true]}")
  println("group false: ${grouped[false]?.reversed() }")
}
