/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package kotlin_playground

import kotlin_playground.sandboxes.DateSandbox
import kotlin_playground.sandboxes.ListSandbox
import kotlin_playground.sandboxes.NullSandbox

class App {
  val greeting: String
    get() {
      return "Hello World!"
    }
}

fun main() {
  println(App().greeting)
  DateSandbox.objectWithValidity()
  ListSandbox.split()
  NullSandbox.nuller()
}
